POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name":"sabrina",
    "email":"nmuhamadfajar04@gmail.com",
    "phone_number": "08121251229",
    "password":"sabrina123",
    "confirm_password":"sabrina123"
}


###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"nmuhamadfajar04@gmail.com",
    "password":"sabrina123"
}

###
GET http://localhost:3000/api/auth/authenticated
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ2OTQxZmE0LTI3ODctNDdiOC05MGQ5LWVjNDZhOTc5YTBjZiIsImlhdCI6MTcwNjc0ODAzMH0.h7ba2enKqFQ8E4_ZRODBf31vzrhP3kbEpAji-bzXj58
